### PR TITLE
fix: allow 2 minutes deviation on schedule cron

### PR DESCRIPTION
**Pull request by fengmk2**
closes https://github.com/eggjs/egg/issues/3209

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by fengmk2** [comment]
cc @luoxiaoji

**Comment by fengmk2** [comment]
3.0.5

**Comment by luoxiaoji** [comment]
> 3.0.5

我用npm i 安装的，大概要等同步了?

**Comment by atian25** [comment]
@luoxiaoji 

hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

**Pull request merged**
