### PR TITLE
feat: rename logrotater => logrotator

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

整个库

##### Description of change

改名后需要重新 publish 一个新库

https://github.com/eggjs/egg/issues/49

### CODE REVIEW

**Comment by popomore** [comment]
@fengmk2 同步下 appveyor

**Comment by popomore** [comment]
codecov  的算法太高级

**Comment by popomore** [comment]
appveyor 我建了个新的

**Comment by popomore** [comment]
补全测试用例了

**Comment by jtyjty99999** [comment]
+1 ..

**Comment by popomore** [comment]
那这个我合了

**Comment by popomore** [comment]
+ egg-logrotator@2.0.0

**Pull request merged**
